### ISSUE TITLE
Chatstates (XEP-0085) trigger MUC rate limiting

### ISSUE THREAD

**Issue by michalrus** [conversejs/converse.js#1152]
… because Converse is sending **two** `<message/>`s immediately after the user hits “send”, instead of **just one** message with appropriate chat state notification –and– an appropriate `<body>`.

These 2 messages, sent one right after another, trigger Ejabberd’s rate limiting, if I set this option to its recommended 400 ms:

```yaml
        modules:
          mod_muc:
            min_message_interval: 0.4
```

More context: https://github.com/processone/ejabberd/issues/2555.

Correct examples: https://xmpp.org/extensions/xep-0085.html#example-detail.
