### ISSUE TITLE
Converse 4.0.4 embedded: shows `chatbox-navback` arrow in header

### ISSUE THREAD

**Issue by ge0rg** [conversejs/converse.js#1296]
On mobile Chrome and Firefox, the `embedded` view will render a navback arrow in the top left corner:

![image](https://user-images.githubusercontent.com/165635/47913200-83f57980-de9b-11e8-9f0e-5c6270fd7d9e.png)

**Comment by ge0rg** [comment]
Workaround:

```css
.chatbox-navback{display:none!important}
```
