### ISSUE TITLE
Unnecessary scrolling viewport on mobile.

### ISSUE THREAD

**Issue by jcbrand** [conversejs/converse.js#1371]
Reported by @ge0rg in #1297

Mobile Chrome dynamically shows/hides the URL bar, but the viewport size seems to be calculated for a hidden URL bar, so the whole thing is always scrolling

The following CSS works around a large part of the problems, but not the Chrome URL bar:

```css
#conversejs{margin:0;left:0;right:0;top:0;bottom:0}
```
