### ISSUE TITLE
Auto list rooms doesn't work.

### ISSUE THREAD

**Issue by stoffel2107** [conversejs/converse.js#1517]
Heyo,

We are implementing a Streaming service and using Ejabberd and converse.js as chat software.
Now since we want ppl to use it natively without errors we'd like to auto list all open rooms.

Using Converse.js 4.1.0
Ejabberd 18.09

Currently, our Converse.js is initialized as follows:
```javascript
converse.initialize({
                authentication: 'anonymous',
                auto_login: true,
                jid: 'anonymous@<domain>.de',
                auto_list_rooms: true,
                auto_away: 300,
                auto_reconnect: true,
                bosh_service_url: '/http-bind',
                message_archiving: 'always',
                view_mode: 'fullscreen',
                animate: true
            });
```

And our ejabberd configures the necessary MUC module as follows:
```yml
mod_muc:
    host: "conference.@HOST@"
    access_create: muc_create
    access_persistent: muc_create
    access_admin: muc_admin
    history_size: 50
    default_room_options:
        persistent: true
        mam: true
```

But rooms aren't auto listed.

I thought of a workaround with the following code:
```javascript
converse.listen.on('ready', function (event) {
                    console.log('ready');
                    converse.chats.open(123);
                    console.log('done');
            });
```

But that, apparently, doesn't work. But I do know how the rooms are called so if there is a way to manually open a chatroom that would be oke.

But the question is, how exactly is auto list rooms working and how do I set it up properly.

Thanks for reading.
Christoph/Stoffel

P.S. I couldn't copy the yml code, therefore, I had to write it myself which could have caused some error in the above yml code which isn't present in the actual code.
