### ISSUE TITLE
Overlayed `view_mode`: Fix main "Chat Contacts" box on the left side + chat toggle boxes upwards

### ISSUE THREAD

**Issue by hakakou** [conversejs/converse.js#2630]
I have an admin inteface, and would really like to 

- put the overlayed main box fixed on the bottom left side of the window instead of the bottom right side. Accordingly, the flyout control box, and then chat boxes, to popup from left to right instead of right to left. 
- Have the various chat toggles go upwards (also the group toggles like ""1 Minimized"") filling up the area of a left column in the browser window and going upwards.
 
Is this possible?

At some point on version 7.x I had the css code below, however it had various problems and is completely broken in 8.0. 

![image](https://user-images.githubusercontent.com/10587642/132101949-e4311755-0fd4-40d7-8dde-47dd34c0735b.png)

My basic objective as you can see was to only used the area in the fixed left column of the window for the small chat toggles, going in an upwards direction.

```css
.chat-head-chatroom > .close-chatbox-button {
    display: none !important;
}

#conversejs.converse-overlayed > .row {
    flex-direction: column-reverse !important;
}

#conversejs .converse-chatboxes {
    position: fixed !important;
    bottom: 40px !important;
    width: 140px !important;
    left: 0px !important;
    right: unset !important;
}

#conversejs .converse-chatboxes {
    left: 0 !important;
    right: unset !important;
}

#conversejs .chatbox-btn.close-chatbox-button.fa-sign-out-alt {
    display: none;
}

#conversejs.converse-overlayed .toggle-controlbox {
    margin: 4px 10px 0 4px !important;
}

#conversejs.converse-overlayed #minimized-chats {
    margin-left: 4px !important;
}

    #conversejs.converse-overlayed #minimized-chats .minimized-chats-flyout {
        flex-direction: column-reverse !important;
        bottom: 100px !important;
    }
```
